import { prisma } from "../lib/prisma";
import { calculateBurnRate, calculateMonthlySavingsRate, calculateRunway, categoryBreakdown, monthlyTrend } from "./analytics";
import { generateText } from "./gemini";
import { getInsightRetentionWindowStart, persistInsightIfNew } from "./insightStore";

function formatCurrency(amount: number) {
    return new Intl.NumberFormat("en-IN", {
        style: "currency",
        currency: "INR",
        maximumFractionDigits: 0,
    }).format(amount);
}

function parseLargeExpenseMessage(message: string): { amount: number; merchant: string } | null {
    const match = message.match(/Large expense of\s+[^\d-]*([\d,]+(?:\.\d+)?)\s+at\s+(.+)$/i);
    if (!match) return null;
    const amount = Number(match[1].replace(/,/g, ""));
    const merchant = match[2]?.trim();
    if (!Number.isFinite(amount) || !merchant) return null;
    return { amount, merchant };
}

function parseMerchantName(message: string): string | null {
    const frequencyMatch = message.match(/You transact with\s+(.+?)\s+\d+\s+times/i);
    if (frequencyMatch?.[1]) return frequencyMatch[1].trim().toLowerCase();

    const behaviorMatch = message.match(/You keep returning to\s+(.+?)\s+-\s+it appears\s+\d+\s+times/i);
    if (behaviorMatch?.[1]) return behaviorMatch[1].trim().toLowerCase();

    return null;
}

export async function generateInsights(limit = 50) {
    const since = getInsightRetentionWindowStart();
    const txs = await prisma.transaction.findMany({
        where: { timestamp: { gte: since } },
        orderBy: { timestamp: "desc" },
        take: limit,
        include: { category: true },
    });
    const generated: any[] = [];
    const addInsight = async (draft: { type: string; message: string; score?: number | null; meta?: unknown }) => {
        const result = await persistInsightIfNew(draft);
        if (result.created) {
            generated.push(result.insight);
        }
    };

    if (!txs.length) {
        return generated;
    }

    const largestTransaction = txs.reduce((current, tx) => (Math.abs(tx.amount) > Math.abs(current.amount) ? tx : current), txs[0]);
    const uniqueMerchants = new Set(txs.map((tx: any) => tx.merchant).filter(Boolean).map((merchant) => String(merchant).toLowerCase())).size;
    await addInsight({
        type: "activity_snapshot",
        message: `Reviewed ${txs.length} transactions across ${uniqueMerchants} merchants. Largest transaction: ${formatCurrency(Math.abs(largestTransaction.amount))} at ${largestTransaction.merchant}.`,
        score: Math.min(100, txs.length * 2),
    });

    const amounts = txs.map((tx: any) => Math.abs(tx.amount)).sort((a: number, b: number) => a - b);
    const median = amounts.length ? amounts[Math.floor(amounts.length / 2)] : 0;
    const largeExpenses = txs
        .filter((tx: any) => median > 0 && Math.abs(tx.amount) > median * 3)
        .sort((a: any, b: any) => Math.abs(b.amount) - Math.abs(a.amount));

    if (largeExpenses.length > 0) {
        const topItems = largeExpenses.slice(0, 3).map((tx: any) => `${formatCurrency(Math.abs(tx.amount))} at ${tx.merchant}`);
        const highestRatio = Math.abs(largeExpenses[0].amount) / Math.max(1, median);
        await addInsight({
            type: "large_expense",
            message: `Detected ${largeExpenses.length} high-value expenses. Top entries: ${topItems.join("; ")}.`,
            score: Math.min(100, highestRatio * 10),
            meta: {
                count: largeExpenses.length,
                median,
                top: largeExpenses.slice(0, 5).map((tx: any) => ({
                    merchant: tx.merchant,
                    amount: Math.abs(tx.amount),
                })),
            },
        });
    }

    // Merchant recurrence is generated by behavior analysis to avoid duplicate cards.

    const savingsData = await calculateMonthlySavingsRate();
    await addInsight({
        type: "savings_rate",
        message: savingsData.monthlyIncome > 0
            ? `Your savings rate is ${Math.round(savingsData.currentMonthSavingsRate)}% this month (${savingsData.savingsMessage}).`
            : `No income transactions were found this month, so your savings rate is currently ${Math.round(savingsData.currentMonthSavingsRate)}%.`,
        score: Math.max(0, Math.min(100, savingsData.currentMonthSavingsRate)),
        meta: savingsData,
    });

    const burnData = await calculateBurnRate();
    if (burnData.previousPeriodHasData) {
        await addInsight({
            type: "burn_rate",
            message: burnData.burnRateChange > 0
                ? `Burn rate increased by ${formatCurrency(Math.abs(burnData.burnRateChange))} versus the previous period.`
                : burnData.burnRateChange < 0
                    ? `Burn rate dropped by ${formatCurrency(Math.abs(burnData.burnRateChange))} versus the previous period.`
                    : "Burn rate is unchanged versus the previous period.",
            score: Math.max(0, Math.min(100, 50 - burnData.burnRateChange)),
            meta: burnData,
        });
    }

    const runwayData = await calculateRunway();
    if (runwayData.runwayMonths !== null) {
        await addInsight({
            type: "runway",
            message: runwayData.runwayMonths < 6
                ? `At the current burn rate, your runway is only ${runwayData.runwayMonths.toFixed(1)} months.`
                : `At the current burn rate, your runway is ${runwayData.runwayMonths.toFixed(1)} months.`,
            score: Math.max(0, Math.min(100, runwayData.runwayMonths * 10)),
            meta: runwayData,
        });
    }

    const monthly = await monthlyTrend(2);
    if (monthly.length >= 2) {
        const previousMonth = monthly[monthly.length - 2];
        const currentMonth = monthly[monthly.length - 1];
        if (currentMonth.expense > previousMonth.expense) {
            await addInsight({
                type: "monthly_spend_trend",
                message: `Monthly spending rose from ${formatCurrency(previousMonth.expense)} to ${formatCurrency(currentMonth.expense)}.`,
                score: Math.min(100, ((currentMonth.expense - previousMonth.expense) / Math.max(1, previousMonth.expense)) * 100),
                meta: monthly,
            });
        }
    }

    const categories = await categoryBreakdown(30);
    if (categories.length > 0) {
        const topCategory = categories[0];
        const totalSpend = categories.reduce((sum, entry) => sum + entry.value, 0);
        const topCategoryShare = totalSpend > 0 ? topCategory.value / totalSpend : 0;
        await addInsight({
            type: "top_category",
            message: `Your largest spending category over the last 30 days is ${topCategory.name}, accounting for ${Math.round(topCategoryShare * 100)}% of tracked spend.`,
            score: Math.min(100, topCategoryShare * 100),
            meta: categories,
        });
    }

    if (txs.length > 10 && process.env.GEMINI_API_KEY) {
        const prompt = `Summarize user's recent transactions and provide 3 concrete insights and one recommended action. Transactions: ${JSON.stringify(txs.slice(0, 50))}`;
        try {
            const resp = await generateText(prompt, { temperature: 0.1, maxTokens: 400, complexity: "simple" });
            await addInsight({ type: "ai_summary", message: resp.text, meta: resp.raw || null });
        } catch (e) {
            // ignore AI errors
        }
    }

    return generated;
}

export async function listInsights(limit = 50) {
    const since = getInsightRetentionWindowStart();
    const raw = await prisma.financialInsight.findMany({
        where: {
            createdAt: {
                gte: since,
            },
        },
        orderBy: { createdAt: "desc" },
        take: Math.max(limit * 5, 200),
    });

    if (raw.length === 0) {
        return raw;
    }

    const aiInsight = raw.find((insight) => insight.type === "ai_summary");
    const largeExpenses = raw.filter((insight) => insight.type === "large_expense");
    const condensed: any[] = [];

    if (aiInsight) {
        condensed.push(aiInsight);
    }

    if (largeExpenses.length > 0) {
        const parsedEntries = largeExpenses
            .map((entry) => parseLargeExpenseMessage(entry.message))
            .filter((entry): entry is { amount: number; merchant: string } => Boolean(entry))
            .sort((a, b) => b.amount - a.amount);

        const newestLargeExpense = largeExpenses[0];
        if (parsedEntries.length > 0) {
            const topEntries = parsedEntries.slice(0, 3).map((entry) => `${formatCurrency(entry.amount)} at ${entry.merchant}`);
            condensed.push({
                id: `large-expense-summary-${newestLargeExpense.id}`,
                type: "large_expense",
                message: `Detected ${parsedEntries.length} high-value expenses in recent history. Top entries: ${topEntries.join("; ")}.`,
                score: Math.max(...largeExpenses.map((entry) => entry.score ?? 0)),
                createdAt: newestLargeExpense.createdAt,
                meta: newestLargeExpense.meta,
            });
        } else {
            condensed.push(newestLargeExpense);
        }
    }

    const merchantCandidates = raw.filter((insight) => insight.type === "merchant_frequency" || insight.type === "behavior_top_merchant");
    const seenKeys = new Set<string>();
    const mergedByType = new Map<string, any>();

    for (const insight of raw) {
        if (insight.type === "ai_summary" || insight.type === "large_expense") {
            continue;
        }

        if (insight.type === "merchant_frequency" || insight.type === "behavior_top_merchant") {
            const merchant = parseMerchantName(insight.message) || "unknown";
            const merchantKey = `merchant:${merchant}`;
            if (seenKeys.has(merchantKey)) {
                continue;
            }
            const candidates = merchantCandidates
                .filter((candidate) => (parseMerchantName(candidate.message) || "unknown") === merchant)
                .sort((a, b) => (b.score ?? 0) - (a.score ?? 0));
            const best = candidates[0] || insight;
            mergedByType.set("merchant_frequency", { ...best, type: "merchant_frequency" });
            seenKeys.add(merchantKey);
            continue;
        }

        if (!mergedByType.has(insight.type)) {
            mergedByType.set(insight.type, insight);
        }
    }

    condensed.push(...mergedByType.values());

    return condensed
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
        .slice(0, limit);
}
