-- RedefineTables
ALTER TABLE "Goal" ADD COLUMN "goalType" TEXT NOT NULL DEFAULT 'PURCHASE';
ALTER TABLE "Goal" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Goal" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "Goal" ADD COLUMN "icon" TEXT;
ALTER TABLE "Goal" ADD COLUMN "color" TEXT;
